version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bridgify
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5432'

volumes:
  pgdata:
